In [24]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, VotingRegressor

In [2]:
df = pd.read_csv('dados_treino_braspress_1_uf.csv')
categorical_columns = df.select_dtypes(include=['str']).columns
df.head()

   MODAL UF DESTINO_x   PESO  VOLUME  VALOR MERCADORIA  VALOR TOTAL FRETE
0      0           GO  38.66       1           5790.16             276.99
1      0           GO  93.00       4           2343.10             276.28
2      1           SP  28.36       1            756.62             178.73
3      0           RJ  24.00       1            371.71             116.32
4      0           PR  18.06       1           1133.55             124.59

In [3]:
scaler = StandardScaler()
encoder = OneHotEncoder(sparse_output=False)

In [4]:
dados_para_scaler = df.drop(['UF DESTINO_x', 'MODAL'], axis=1)
scaled_data = scaler.fit_transform(dados_para_scaler)
df_processado = pd.DataFrame(
    scaled_data, 
    columns=dados_para_scaler.columns, 
    index=dados_para_scaler.index
)
df_processado = pd.concat([df_processado, df[['MODAL', 'UF DESTINO_x']]], axis=1)
df_processado.head()

       PESO    VOLUME  VALOR MERCADORIA  VALOR TOTAL FRETE  MODAL UF DESTINO_x
0 -0.247757 -0.614842          5.289085           0.635545      0           GO
1  0.946754  1.477566          1.391934           0.629687      0           GO
2 -0.474173 -0.614842         -0.401696          -0.175153      1           SP
3 -0.570016 -0.614842         -0.836865          -0.690069      0           RJ
4 -0.700590 -0.614842          0.024451          -0.621837      0           PR

In [5]:
encoded_data = encoder.fit_transform(df_processado[categorical_columns])

In [6]:
encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(categorical_columns)
)

final_df = pd.concat(
    [df_processado.drop(columns=categorical_columns), encoded_df],
    axis=1
)

In [7]:
X = final_df.drop('VALOR TOTAL FRETE', axis=1)
y = final_df['VALOR TOTAL FRETE']
final_df.head()

,PESO,VOLUME,VALOR MERCADORIA,VALOR TOTAL FRETE,MODAL,UF DESTINO_x_AL,UF DESTINO_x_AM,UF DESTINO_x_BA,UF DESTINO_x_DF,UF DESTINO_x_ES,...,UF DESTINO_x_PI,UF DESTINO_x_PR,UF DESTINO_x_RJ,UF DESTINO_x_RO,UF DESTINO_x_RR,UF DESTINO_x_RS,UF DESTINO_x_SC,UF DESTINO_x_SE,UF DESTINO_x_SP,UF DESTINO_x_TO
0,-0.247757,-0.614842,5.289085,0.635545,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.946754,1.477566,1.391934,0.629687,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.474173,-0.614842,-0.401696,-0.175153,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-0.570016,-0.614842,-0.836865,-0.690069,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.700590,-0.614842,0.024451,-0.621837,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

KNN Regressor

In [9]:
knn = KNeighborsRegressor()
knn.fit(X_train, y_train)

KNeighborsRegressor()

In [10]:
knn.score(X_train, y_train)

0.7459178890495772

In [11]:
knn.score(X_test, y_test)

0.4312935183868968

Decision Tree Regressor

In [12]:
decision = DecisionTreeRegressor(random_state=0)
decision.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [13]:
decision.score(X_train, y_train)

0.9923834414789828

In [14]:
decision.score(X_test, y_test)

-0.05892775581583787

Linear Regression

In [16]:
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)

LinearRegression()

In [17]:
linear_regressor.score(X_train, y_train)

0.8036898550979473

In [18]:
linear_regressor.score(X_test, y_test)

0.5008386469634611

Random Forest Regression

In [21]:
random_forest = RandomForestRegressor()
random_forest.fit(X_train, y_train)

RandomForestRegressor()

In [22]:
random_forest.score(X_train, y_train)

0.9443986743821147

In [23]:
random_forest.score(X_test, y_test)

0.3834235898910118

Voting Regressor

In [25]:
voting = VotingRegressor([('knn', knn), ('decision_tree', decision), ('linear_regressor', linear_regressor), ('random_forest', random_forest)])
voting.fit(X_train, y_train)

VotingRegressor(estimators=[('knn', KNeighborsRegressor()),
                            ('decision_tree',
                             DecisionTreeRegressor(random_state=0)),
                            ('linear_regressor', LinearRegression()),
                            ('random_forest', RandomForestRegressor())])

In [26]:
voting.score(X_train, y_train)

0.9252561437249573

In [27]:
voting.score(X_test, y_test)

0.4435429583425001